### ISSUE TITLE
Error in as.DocumentTermMatrix | unused argument (col = col)

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#100]
Creating a Term-Document-Matrix works great. Using GermaParl as an example:

```
library(polmineR)
use("GermaParl")
sp <- as.speeches("GERMAPARL", s_attribute_name = "speaker")
tdm <- as.TermDocumentMatrix(sp, p_attribute = "word")
```

However, creating a Document-Term-Matrix throws an error at the very beginning of the process. Using the same speech_bundle as before

```
dtm <- as.DocumentTermMatrix(sp, p_attribute = "word")
```

results in: 

>  Error in .local(x, ...) : unused argument (col = col) 

First observed in polmineR_0.7.11.9034

**Comment by ablaette** [comment]
This is fixed in polmineR_0.7.11.9035. First, I had thought this is a no-brainer, but finding the problem took me some time at the end. The `as.TermDocumentMatrix`-method is available for many classes, but in fact it is defined only for `partition_bundle` and `bundle`.  The implementation relies heavily on calls to `callNextMethod()`, but I had not anticipated, that a jump back to the top of the class hierarchy (i.e. `subcorpus_bundle`) will occur, when `as.DocumentTermMarix` calls `as.TermDocumentMatrix`. Let's leave it with this ...
