### ISSUE TITLE
enriching of kwic object doesn't work anymore

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#102]
In a blog entry you describe a workflow to enrich a KWIC object: https://polmine.github.io/posts/2019/05/17/Towards-polmineR-v0.8.0-A-new-annotation-workflow.html

You create the object as you normally would.

`x <- kwic("GERMAPARL", query = "Integration")`

and enrich it in the next step, adding an extra 5 words.

`x <- enrich(x, extra = 5)`

However, in `polmineR 0.7.11.9036` this results in an error:

>  Error in setnames(.Object@stat, old = "-1", new = "right_extra") : 
  Items of 'old' not found in column names: -1. Consider skip_absent=TRUE.

**Comment by ablaette** [comment]
There is a new version on the dev branch (v0.7.1.9041) addressing this issue. The new `enrich()`-functionality we had introduced a few weeks was a nice proof-of-concept, but not yet generic and robust, so that changes on the `kwic` object (a different order of columns) could easily result in the error.

The rework will now also allow to add extra context when the p-attribute is different from "word" (lemma, for instance). For instance:

```{r}
library(polmineR)
use("GermaParl")

x <- kwic("GERMAPARL", query = "Integration", p_attribute = "lemma")
x <- enrich(x, extra = 5)
```

**Comment by ChristophLeonhardt** [comment]
Thank you,  it works! As far as I am concerned, this issue can be closed.
