### ISSUE TITLE
Slow partition_bundle if input is partition

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#112]
It is not necessarily a huge issue, but something I noticed: Creating a partition bundle based on a partition takes quite a bit longer than creating it based on the corpus itself. 

In the following experimental setup (which hopefully is some kind of meaningful), it takes about five times as long to generate a partition bundle from a partition:

```
library(polmineR)
use("GermaParl")
library(microbenchmark)
p_germaparl <- partition("GERMAPARL", interjection = FALSE) 
microbenchmark(
  partition_bundle("GERMAPARL", s_attribute = "year"),
  partition_bundle(p_germaparl, s_attribute = "year"), 
  times = 10L
)
```

| partition_bundle("GERMAPARL", s_attribute = "year") 	| 5.131501  	|
|-----------------------------------------------------	|-----------	|
| partition_bundle(p_germaparl, s_attribute = "year") 	| 27.969721 	|

Mean duration in seconds.

**Comment by PolMine** [comment]
Thanks for reporting the poor performance of `partition_bundle()`. I am quite confident that we can do much better. In fact, the new workflow introduced last year of subsetting and splitting `corpus` objects to get `subcorpus` and `subcorpus_bundle` objects, respectively, resulted in a huge performance boost. 

See the following benchmark I have run, picking up your approach.

```r
library(polmineR)
use("GermaParl")
library(microbenchmark)

p <- partition("GERMAPARL", year = 2001)
sc <- corpus("GERMAPARL") %>% subset(year == 2001)

microbenchmark(
  partition_bundle(p, s_attribute = "speaker"),
  split(sc, s_attribute = "speaker"),
  times = 10L
)
```
The result is as follows:

| partition_bundle(p, s_attribute = "speaker") 	| 34.53	|
|----------------------------------------------	|--------	|
| split(sc, s_attribute = "speaker")                  	| 0.21	|

I guess this improvement is really what we are looking for. When implementing the `split()`-method for `partition` objects, I somewhat deliberately refrained from infusing the performance gain into the `partition_bundle()`-method, to make sticking to the old workflow painful.

The weakness of this scheme is that I am not yet offering clear documentation and guidance so that users know about the `split()`-way of doing things. So I think the backwardness of `partition_bundle()` needs to be overcome. The only challenge is to think carefully how to achieve and implementation that follows the DRY principle.

**Comment by PolMine** [comment]
To speed up the making of `partition_bundle` objects, the method for `corpus` and `partition` input now relies on the corresponding (fast) `split()`-methods for these classes. Using our previous code for benchmarking, this is the result:

| partition_bundle(p, s_attribute = "speaker") 	| 0.20	|
|----------------------------------------------	|--------	|
| split(sc, s_attribute = "speaker")                  	| 0.21	|

So I think we are doing quite well to make `partition_bundle()` catch up with the speed of `split()`.

The remaining limitation is that `split()` is not capable to handle a nested XML structure. This is why we should keep this issue open.

**Comment by ChristophLeonhardt** [comment]
I am not entirely sure why I did not use `subset()` and `split()` in the first place knowing that this should be a fair bit faster than `partition_bundle()` in any case. Also, I see your point of incentivizing the switch to `subset()` and `split()`.  Nevertheless, I am glad that you could achieve such an improvement for the `partition_bundle` method. As expected, both approaches are now a lot faster than the way I described before.
