### ISSUE TITLE
polmineR - Installation issues

### ISSUE THREAD

**Issue by hsang** [PolMine/polmineR#13]
Dear all,

I have some problems installing two packages from polmineR. More precisely _PolMine/polmineR.graph_ and _PolMine/polmineR.shiny_:
- PolMine/polmineR.graph:

_ERROR: dependency ‘three’ is not available for package ‘polmineR.graph'_

- PolMine/polmineR.shiny:

_No methods found in "polmineR" for requests: keyness
Error in conformMethod(signature, mnames, fnames, f, fdef, definition) : 
  in method for ‘partition’ with signature ‘.Object="shinySession"’: formal arguments (.Object = "shinySession", ... = "shinySession") omitted in the method definition cannot be in the signature
Error : unable to load R code in package ‘polmineR.shiny’
ERROR: lazy loading failed for package ‘polmineR.shiny_

Thank you for your help.

Best,
Hugo

**Comment by ablaette** [comment]
Dear Hugo,

thanks a lot for bringing up these issues. The dependency 'three' for loading the polmineR.graph-package is available at GitHub on my personal account (github.com/ablaette) because it is more generic. I would leave a hint where the package can be found in the README of the polmineR.graph-package and close the issue here.

And you remind me that polmineR.shiny needs to be removed from GitHub. I have moved the shiny apps into the polmineR-package. The app can be started by calling polmineR(). Caution: A partition needs to present in the global environment. And, admittedly, the shiny app is 'sugar' (not part of the core of the package), and it still needs improvement. 

Thus, I'll close the issue. Thanks again!
Andreas

**Comment by hsang** [comment]
Thank you very much Andreas.

Hugo

**Comment by ablaette** [comment]
more than welcome, thanks for your feedback! the new version is available on the master branch at github now, and has passed the checks at CRAN. Kindly, Andreas

Am 16.09.2016 um 13:38 schrieb hsang <notifications@github.com<mailto:notifications@github.com>>:


Thank you very much Andreas.

Hugo
