### ISSUE TITLE
Suppress warning messages for large DataTable objects

### ISSUE THREAD

**Issue by ablaette** [PolMine/polmineR#145]
Displaying large kwic objects (many hits / large context) may result in a warning that the data may be to big for for client-side DataTables. See the following example:

```r
library(polmineR)
k <- kwic("GERMAPARL", "Integration")
show(k)

# Warning:
# In instance$preRenderHook(instance) :
# It seems your data is too big for client-side DataTables. You may consider server-side
# processing: https://rstudio.github.io/DT/server.html
```

If polmineR is used in a local setting, the warning is misleading. Server and client are the same machine, there will not be a problem. Thus, it would make sense to suppress the message that is fairly confusing.

In fact, the code for `DT::datatable()` checks whether option `DT.warn.size` is defined and / or `TRUE` before issuing the warning. Thus, the warning can be suppressed as follows:

```r
options("DT.warn.size" = FALSE)
show(k)
```

An argument `warn` could be used to set the option to `FALSE` and to suppress the warning message.

**Comment by ChristophLeonhardt** [comment]
I hope it is okay when I chime in like this: I would argue that while misleading in wording, the warning can be useful as it clearly indicates when a table is really large and hence showing it might cause problems on machines with limited resources. Otherwise one might wonder why the machine starts running sluggishly after performing a kwic analysis. 

That being said, there are at least three things I can think of that support the suppression of the warning: 

* I am not sure at which point data.table starts showing this warning. Might be rather early and meaningless.
*  when the warning is shown, the table is shown anyway, so it is rather inconsequential. 
* the wording indeed is misleading as it suggests a solution that isn't there.

All in all, I wouldn't mind keeping the warning but including the solution `options("DT.warn.size" = FALSE)` in the documentation / training material. Alternatively "try-catching" the warning and replacing it with a hint that the table will be rather large might work, too. In any case, this would just allow to spot large tables quickly, purely for convenience, so maybe suppressing the warning altogether wouldn't really hurt either.

**Comment by ablaette** [comment]
Thanks for your thoughts and arguments! This is a mental note rather than a direct response yet. This is how we come somewhat close to anticipating when the warning is shown:

```r
library(polmineR)

k <- kwic("GERMAPARL", "Integration")

object.size(format(k[1:7946], align = FALSE)) # 1500664 bytes
show(k[1:7946])

object.size(format(k[1:7945], align = FALSE)) # 1500480 bytes
show(k[1:7945])
```

**Comment by ablaette** [comment]
A new dev version of polmineR now includes a preliminary solution. There is a new option `polmineR.warn.size`. If you set it as `FALSE`, the warnings are omitted: Internally, option `DT.warn.size` is set as `FALSE` before producing the table, and the original value is restored afterwards. 

The documentation object for the package as a whole (i.e. what you see when calling `?polmineR` has been expanded to include an itemized list of package options. This has been missing before, and it is still only rudimentary. The option `polmineR.warn.size` is explained at length. Maybe it is too long and technical already.

**Comment by ablaette** [comment]
Now I also added a reference to the option `polmineR.warn.size` in the documentation of `kwic()`, hoping that this will be enough.
