### ISSUE TITLE
as.DocumentTermMatrix() returns wrong class

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#146]
`as.DocumentTermMatrix()` returns an object of class `TermDocumentMatrix` which, I assume, has some odd consequences when printing the summary of the object. I am not sure if there are more problems to this however. 

See the following example. 

```
dtm <- polmineR::as.DocumentTermMatrix("GERMAPARLMINI", s_attribute = "party", p_attribute = "word")
```

Here

```
class(dtm)
```

returns

> [1] "TermDocumentMatrix"    "simple_triplet_matrix"

and 

```
dtm
```

returns

> <<TermDocumentMatrix (terms: 6, documents: 18148)>>
Non-/sparse entries: 33857/75031
Sparsity           : 69%
Maximal term length: 15
Weighting          : term frequency (tf)

Here, the statistics are obviously switched (it should be 6 documents and 18148 terms. The Maximal term length indicates the max length of the document names (the max term length is 40).

**Comment by jkrss** [comment]
Hi
I noticed the same problem. The mix-up in the statistics also happens when I use 

`dtm <- polmineR::as.TermDocumentMatrix("GERMAPARLMINI", s_attribute = "party", p_attribute = "word")`

 This also has consequences for operations on a term-document-matrix using the tm-package (e.g., findFreqTerms or findAssocs).

Best
Julia

**Comment by ablaette** [comment]
A bang-your-head-error: The `as.DocumentTermMatrix()` method at the very end does:

```r
class(dtm) <- c("DocumentTermMatrix", "simple_triplet_matrix")
```

Just fixed it. Solution on the dev branch.
