### ISSUE TITLE
CRAN installation

### ISSUE THREAD

**Issue by cgnguyen** [PolMine/polmineR#148]
I am using polmineR and germaparl for teaching, and a lot of my students are having a hard time installing the packages, since they are no longer on CRAN and the devtools installation is finicky at best. Is there any update on when/ if a CRAN version will be available?

**Comment by ablaette** [comment]
Great to hear that you are using polmineR. But it is really bad to hear that my worst nightmare has become true, i.e. that people are having a hard time because polmineR is temporarily not available via CRAN.

I have written [this blogpost](https://polmine.github.io/posts/2020/06/30/Reuniting-the-PolMine-family.html) that explains what is going on. To put it in a nutshell: New CRAN checks that were difficult to anticipate caused that an update of RcppCWB was not available in time. RcppCWB was archived. All packages depending on RcppCWB were archived, i.e. polmineR and cwbtools were removed from CRAN.

RcppCWB is back at CRAN already. All further releases are awaiting CRAN approval to be re-published. But it is taking time as CRAN scrutiny is very different from what it was one or two years ago, to safeguard quality when everybody wants to see his/her package at CRAN. Everything can be fixed, there is no substantial obstacle at all. But it may still take two or three days for polmineR (and cwbtools) to be available via CRAN again.

To offer a convenient installation mechanism as a backup, the release candidates I have prepared (including Windows and macOS binaries) are available via the "drat" repository of the PolMine Project. This is a CRAN-style repository that we host ourselves. The  conventional `install.packages()` function will check the availability of packages at this repository if the repository is registered first. So this is what you can do, and please share it with your students:

```r
install.packages("drat")
drat::addRepo("polmine")
install.packages("polmineR")
install.packages("cwbtools")
```

One potential limitation may be that I could not prepare binaries for older R versions, only for current ones (R 4.0. / R 4.1).  It may be necessary for Windows users to have [Rtools](https://cran.r-project.org/bin/windows/Rtools/) installed if you want to avoid the updatee to R 4.1.

Please let me know whether that works for you and your students. I am very well aware of the situation and working as hard as I can to get this fixed. Feedback whether the backup installation works is highly appreciated!

**Comment by cgnguyen** [comment]
Thank you so much for the detailed response!  That actually did the trick. But also, I think a lot of packages are having problems with the stricter CRAN rules now, so I think it is not really your fault. Also fwiw, the students liked the program, and I hope they will use it in their own work, too.
