### ISSUE TITLE
cpos | as.corpusEnc produces NA queries

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#151]
First: I am not sure where to file the cqp related issues as this often is related to RcppCWB, however I think in this case `polmineR` is at fault. 

# Problem

The cpos function will try to convert a query from the local encoding (in my case this is UTF-8) to the corpus encoding (which, in this case, is latin1) here:

```
  query <- as.corpusEnc(query, corpusEnc = .Object@encoding)
```

As soon as the query contains a non-convertible (?) character, the return value of as.corpusEnc() will be NA. This isn't great but the issue is that if the cqp parameter is set to TRUE in the function making the cpos-call, this will lead to the error:

> Error in if (!substr(query, start = nchar(query), stop = nchar(query)) ==  : 
  missing value where TRUE/FALSE needed

Due to this check: 

```
RcppCWB::cqp_query(corpus = .Object@corpus, query = q)
```

Interestingly, when you don't set the cqp parameter explicitly, whether cqp is TRUE is determined by the cpos method itself which then identifies that the query now is NA. This leads to cqp = FALSE which circumvents the check. Then you get "... no hits for query:  NA" message in the end which isn't great either but doesn't result in an error.

# Reproducible Example

The easiest example would be 

```
kwic("GERMAPARLMINI", query = '[word = "–"]', cqp = TRUE, regex = TRUE)
```

The hyphen apparently cannot be converted to latin1. 

# Side note

`iconv`, which produces the NA, could be modified in a way which would allow the replacement of individual faulty characters instead of returning the entire query as NA. This would get rid of the error, but certainly would alter the textual data itself which should be avoided.

**Comment by Studentenfutter** [comment]
I just encountered a similar issue when working with turkish organisation names and almost opened a new issue.

```
as.corpusEnc("ADD Dortmund Atatürkçü Düşünce Derneği Dortmund", corpusEnc = "latin1")
```
`[1] NA`

Is there a "quick fix" other then to change the encoding of the whole corpus?

**Comment by Studentenfutter** [comment]
After some research I found a quick fix which works in my case because I am querying with regular expressions:

`iconv("ADD Dortmund Atatürkçü Düşünce Derneği Dortmund", to = "latin1", sub = ".")`

Instead of printing `NA`, every non-convertable character gets replaced by a dot, wich equals to any character in RegEx.

**Comment by ablaette** [comment]
Using the `sub` argument is a brilliant solution, but ... the character that cannot be converted will be represented by two dots and the regex will not work. Some post-cleaning might be necessary.

Another option would be:

```r
stringi::stri_encode(str = "Düşünce", from = "UTF-8", to = "latin1")
```
# "Dü\032ünce"

**Comment by ablaette** [comment]
I just pushed a new polmineR version (v0.8.5.9013) on the dev branch that implements a solution. To cut a long story short, I think it is best to work with telling warnings.

Running the following code ... 

```r
library(polmineR)
vec <- c("Atatürkçü", "Düşünce", "Derneği")
as.corpusEnc(vec, corpusEnc = "latin1")
```
... will now lead to the following warnings:

> 1: In as.corpusEnc(vec, corpusEnc = "latin1") :
>  Character string 'Düşünce' to be converted from encoding 'UTF-8' to targert encoding 'latin1' contains single characters
> ('ş') that are non-convertible. The result is an NA character vector which may provoke errors. Recommended solution:
> Substitute non-convertible single characters with an appropriate equivalent or a regular expression metacharacter such as '.'.
> 2: In as.corpusEnc(vec, corpusEnc = "latin1") :
>  Character string 'Derneği' to be converted from encoding 'UTF-8' to targert encoding 'latin1' contains single characters >('ğ') that are non-convertible. The result is an NA character vector which may provoke errors. Recommended solution:
> Substitute non-convertible single characters with an appropriate equivalent or a regular expression metacharacter such as '.'.

I think using the argument `sub` as suggested by Studentenfutter is a good and interesting option, but if you set `sub`  to ".", non-convertible characters are replaced by '..' rather than '.' . So some further postprocessing would be necessary. What is more, the query would be changed implicitly without the user knowing it. It may result in matches that were not intended by the user.

Even if it may be tedious, I think it is best if the user substitutes characters explicitly and consciously, guided by the warning I suggest. It will be good to hear whether you agree.

**Comment by ablaette** [comment]
Today, R 4.2.0 has been released, which brings UTF-8 to Windows. Many issues we have seen will be gone, including this one. In case we still have the warnings I introduced .
