### ISSUE TITLE
Subsetting function limited in remote_corpus class

### ISSUE THREAD

**Issue by Thore91** [PolMine/polmineR#161]
When attempting to subset a remote_corpus class object by using an argument longer than 1, I get the following error code

`sub <- subset(faz, article_id == c("FAS_200109_11098", "FAS_200109_11099", "FAS_200109_11100", "FAS_200109_11101", "FAS_200109_11102", "FAS_200109_11103"))
Error in ocpu_exec(fn = "subset", corpus = x@corpus, server = x@server,  : 
  Bad Request (HTTP 400).
In addition: Warning message:
In charToRaw(enc2utf8(val)) :
  argument should be a character vector of length 1
all but the first element will be ignored`

**Comment by PolMine** [comment]
Thanks! A good one. First I thought you had gotten the logical expression wrong, it should be a `%in%` and not a `==`. So this should work:

```r
sub <- subset(faz, article_id %in% c("FAS_200109_11098", "FAS_200109_11099", "FAS_200109_11100", "FAS_200109_11101", "FAS_200109_11102", "FAS_200109_11103"))
```

But this bug is hard to understand, as the command starts to fail if the vector to check against is longer than four elements.

Indeed, the error results from a behavior of `deparse()` I had not anticipated. Before passing the expression to the remote server, it is passed into `substitute()` just to be deparsed again. But if the number of characters exceeds a limit defined by the argument `width.cutoff` of `deparse()`, you get a character vector longer than 1 resulting in the error you report. 

See the result of the following minimal example.

```r
foo <- deparse(list(subset = substitute(article_id %in% c("FAS_200109_11098", "FAS_200109_11099", "FAS_200109_11100", "FAS_200109_11101"))))
foo
```
[1] "list(subset = article_id %in% c(\"FAS_200109_11098\", \"FAS_200109_11099\", "
[2] "    \"FAS_200109_11100\", \"FAS_200109_11101\"))"

And to reproduce the error you report:

```r
charToRaw(enc2utf8(foo))
```
In charToRaw(enc2utf8(val)) : argument should be a character vector of length 1 all but the first element will be ignored

One option to resolve the issue would be to define a higher value for `width.cutoff` - but for a reason I do not understand, the maximum value you can set is 500. So I think the safest way to address this is to paste the results of `deparse()` into a single string. I will let you know

**Comment by ablaette** [comment]
I just pushed a new polmineR version on the dev branch that addresses the issue. Run `devtools::install_github("PolMine/polmineR", ref = "dev") to install it. 

This is the example I used to check whether it works as intended:

```r
library(polmineR)
faz <- corpus("MIGPRESS_FAZ", server = "http://faz.migpress.de", restricted = TRUE)
sub <- subset(faz, article_id %in% c("FAS_200109_11098", "FAS_200109_11099", "FAS_200109_11100", "FAS_200109_11101", "FAS_200109_11102", "FAS_200109_11103"))
```

Please let me know whether it works for you.

**Comment by Thore91** [comment]
Thanks, that fixed it!

**Comment by Thore91** [comment]
There is one more 'problem' with the subsetting. Say I would like to subset based on a very large amount of article_ids (e.g. around 1,000) I would like to pass them through a vector:

```
vector <- c("FAS_200109_11098", "FAS_200109_11099", "FAS_200109_11100", "FAS_200109_11101", "FAS_200109_11102", "FAS_200109_11103")
sub <- subset(faz, article_id %in% vector)
```

This still produces an error unfortunately:

Error in ocpu_exec(fn = "subset", corpus = x@corpus, server = x@server,  : 
  Bad Request (HTTP 400).
