### ISSUE TITLE
Subsetting function limited in remote_corpus class // Part 2

### ISSUE THREAD

**Issue by Thore91** [PolMine/polmineR#162]
There is one more 'problem' with the subsetting. Say I would like to subset based on a very large amount of article_ids (e.g. around 1,000) I would like to pass them through a vector:

```
vector <- c("FAS_200109_11098", "FAS_200109_11099", "FAS_200109_11100", "FAS_200109_11101", "FAS_200109_11102", "FAS_200109_11103")
sub <- subset(faz, article_id %in% vector)
```

This still produces an error unfortunately:

Error in ocpu_exec(fn = "subset", corpus = x@corpus, server = x@server,  : 
  Bad Request (HTTP 400).

_Originally posted by @Thore91 in https://github.com/PolMine/polmineR/issues/161#issuecomment-702693228_

**Comment by ablaette** [comment]
The problem is that upon evaluating the expression in your call, the OpenCPU will 
not have the vector with ids available. The solution is to generate a call with the 
evaluated variable locally and to pass it to the server. This requires a minor update
of the `subset()` method that you will find in the latest polmineR version at the 
dev branch. 

See the following example!

```r
library(polmineR)

faz <- corpus("MIGPRESS_FAZ", server = "http://faz.migpress.de", restricted = TRUE)
ids <- s_attributes(faz, s_attribute = "article_id")
ids_sample <- sample(ids, 1000)
x <- substitute(article_id %in% vector, list(vector = ids_sample))
sc <- subset(faz, x)
```
