### ISSUE TITLE
as.cqp() returns less results then expected

### ISSUE THREAD

**Issue by Studentenfutter** [PolMine/polmineR#167]
As a workaround till hopefully #150 is implemented I convert a list of queries using `as.cqp()`.
When using this function, my input `Alternative für Deutschland` gets converted into `"\"Alternative\" \"für\" \"Deutschland\""`

However, when I use this to query a corpus, the produced query returns less results than a "manual converted" query:
`count(faz, query = '[lemma="Alternative"] [lemma="für"] [lemma="Deutschland"]', p_attribute= "lemma", cqp = TRUE)`
| Query | Count |
|---|---|
| "\"Alternative\" \"für\" \"Deutschland\"" | 305 |
| '[lemma="Alternative"] [lemma="für"] [lemma="Deutschland"]' | 306 |

Upon further inspection, the missing match from the `as.cqp()` version seems to be this one:
| article_id | left | node | right |
| --- | --- | --- | --- | 
| FAZ_201706_13026 | . #unknown# Verhältnis ? 5 | Alternative für Deutschland | : Wahlwerbung die KPD , |

It seems that a lemma followed by an punctuation character provokes this. Maybe this is also corpus specific as I am using the  openCPU remote corpus `MigPress`?

**Comment by ablaette** [comment]
My apologies for the late reply. My take on this is that the queries are just different: Your self-generated query performs the search on the p-attribute "lemma", the other one on the p-attribute "word". 

In the corpus I use, I also get different results - unless I consider that the lemma-based query will match more because it will also match the plural of "Alternative". Thus if I alter the query somewhat ... 

```{r}
count(faz, query = '"Alternative(|n)" "für" "Deutschland"', cqp = TRUE)
count(faz, query = '[lemma = "Alternative"] [lemma = "für"] [lemma = "Deutschland"]', cqp = TRUE)
```

... results are identical. I have no reason to think that it is the punctuation. (Please re-open the issue if I am mistaken.)
