### ISSUE TITLE
count() seems to have difficulties with dplyr's group_by_() function

### ISSUE THREAD

**Issue by Thore91** [PolMine/polmineR#168]
when running the simple `count()` command (on both corpus and remote_copus class) I am getting and error:

> Error in UseMethod("group_by_") : 
>   no applicable method for 'group_by_' applied to an object of class "c('remote_subcorpus', 'subcorpus', 'regions', 'slice', 'corpus')"
> In addition: Warning message:
> `group_by_()` is deprecated as of dplyr 0.7.0.
> Please use `group_by()` instead.
> See vignette('programming') for more help

to reproduce in polmineR developer version 0.8.5.9005
```
query <- c('"[aA]syl."', '"[iI]mmigrant."')
parl <- corpus("GERMAPARLMINI")
count(parl, query = query)
```

**Comment by ablaette** [comment]
I am afraid this is an issue I am aware of. Both polmineR and dplyr define a count method.
The different method definitions may conflict and cause the error if polmineR is loaded 
after dplyr. See the following examples to be run in fresh sessions.

If you do not load dplyr at all, no problem.

```r
library(polmineR)
count("GERMAPARLMINI", query = c('"[aA]syl."', '"[iI]mmigrant."'))
```

If you load dplyr after polmineR - here is the error. You see it after a couple of warnings
that objects, including this one: 
The following object is masked from ‘package:polmineR’: count

```r
library(polmineR)
library(dplyr)
count("GERMAPARLMINI", query = c('"[aA]syl."', '"[iI]mmigrant."'))
```

Yet if you load polmineR after dplyr, everything works.

```r
library(dplyr)
library(polmineR)
count("GERMAPARLMINI", query = c('"[aA]syl."', '"[iI]mmigrant."'))
```

I am very well aware that many people will want to use polmineR in combination with
dplyr. But I have not yet found a way to create out-of-the-box harmony between polmineR
and dplyr without having to make dplyr a polmineR dependency. So far, I had avoided 
this, because it would create a huge overhead of packages that need to be installed - 
all kinds of dependenceis if dplyr, in fact the greatest part of the tidyverse.

I hope that loading polmineR after dplyr would be a solution for you, for the time
being?
