### ISSUE TITLE
Too few arguments-Error when "showing" a partition object

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#170]
On line 35 of the partition.R script (in the `show()` method for partition) there is a minor bug which breaks the display of the s-attributes summary in the partition. The error occurs when a partition object is called and there is more than one s-attribute to display. Tested on polmineR_0.8.5.9008.

```
library(polmineR)
use("polmineR")
P <- partition("GERMAPARLMINI", speaker = "Volker Kauder", date = "2009-11-10")
P
```

> Error in sprintf("%-20s") : too few arguments

The solution seems quite clear: A paranthesis is misplaced in `sprintf()`

Is:

```
    if (length(s) > 1) {for (i in length(s)) message(sprintf("%-20s"), s[i]) }
```

Should be:

```
    if (length(s) > 1) {for (i in length(s)) message(sprintf("%-20s", s[i])) }
```

Bonus:

There is another small oversight in the line the sprintf-error occurs in: Once fixed, it will still only show the very last additional s-attribute (even if the partition is created based on more than two s-attributes). Probably what you might want to do is to print all s-attributes after the first. In this case

```
    if (length(s) > 1) {for (i in 2:length(s)) message(sprintf("%-20s", s[i])) }
```

might be the way to go.

**Comment by ablaette** [comment]
Wonderful mindfuck. At first I thought, that you offer the perfect solution. But ... it gets you this result:

** partition object **
corpus:             GERMAPARLMINI
name:               
s-attributes:       speaker = Volker Kauder
date = 2009-11-10   
cpos:                83 pairs of corpus positions
size:                3956 tokens
count:               not available

Actually the bracket was at the correct location! But you are perfectly right that `2L:length(s)` had been missing and I should have inserted "" rather than s[i] to get the indentation right. 

The correct solution is:
```r
if (length(s) >= 2L) for (i in 2L:length(s)) message(sprintf("%-20s", ""), s[i], appendLF = TRUE)
```
I also streamlined the other indents, so now we get:

** partition object **
corpus:             GERMAPARLMINI
name:               
s-attributes:      speaker = Volker Kauder
                          date = 2009-11-10
cpos:                 83 pairs of corpus positions
size:                  3956 tokens
count:               not available

**Comment by ChristophLeonhardt** [comment]
Ah, yes. As far as I saw it the error occurred because `sprintf` was missing any insertion and I assumed that inserting the s-attribute was desired. However, this solution is certainly prettier. Thanks for the swift response. I think the issue can be closed.
