### ISSUE TITLE
Diverse errors with cqp after the last update

### ISSUE THREAD

**Issue by mxi-hug** [PolMine/polmineR#22]
After the last polmineR update ("dev" branch from today), a number of functions working with cqp are broken. 

`count("PLPRBT", query = '"Ungleichh.*"', cqp = TRUE)`
returns
```
Fehler in count/total : nicht-numerisches Argument für binären Operator
3. .local(.Object, ...)
2. count("PLPRBT", query = "\"Ungleichh.*\"", cqp = TRUE)
1. count("PLPRBT", query = "\"Ungleichh.*\"", cqp = TRUE)
```

`matches("PLPRBT", query = '"Ungleichh.*"', cqp = TRUE)`
leads to
```
Fehler in apply(cposHits, 1, function(x) paste(CQI$cpos2str(.Object@corpus, : dim(X) must have a positive length
10. stop("dim(X) must have a positive length")
9. apply(cposHits, 1, function(x) paste(CQI$cpos2str(.Object@corpus, pAttribute, x[1]:x[2]), collapse = " "))
8. FUN(X[[i]], ...)
7. lapply(query, function(x) { cposHits <- cpos(.Object = .Object, query = x, cqp = cqp, pAttribute = pAttribute) if (is.null(cposHits)) ...
6. .local(.Object, ...)
5. matches(.Object = C$as.partition(), query = query, cqp = cqp, pAttribute = pAttribute)
4. matches(.Object = C$as.partition(), query = query, cqp = cqp, pAttribute = pAttribute)
3. .local(.Object, ...)
2. matches("PLPRBT", query = "\"Ungleichh.*\"", cqp = TRUE)
1. matches("PLPRBT", query = "\"Ungleichh.*\"", cqp = TRUE)
```

and similarly

`kwic("PLPRBT", query = '"Ungleichh.*"', cqp = TRUE)`
```
Fehler in apply(hits, 1, function(row) { : dim(X) must have a positive length
5. stop("dim(X) must have a positive length")
4. apply(hits, 1, function(row) { left <- c((row[1] - left - 1):(row[1] - 1)) right <- c((row[2] + 1):(row[2] + right + 1)) list(left = left[left > 0], node = c(row[1]:row[2]), right = right[right <= ...
3. .local(.Object, ...)
2. kwic("PLPRBT", query = "\"Ungleichh.*\"", cqp = TRUE)
1. kwic("PLPRBT", query = "\"Ungleichh.*\"", cqp = TRUE)

```

Without cqp, everything works fine.

**Comment by PolMine** [comment]
Thanks a lot for raising the issue! I fixed the pug and pushed an updated polmineR version to the dev branch. To install it: `devtools::install_github("PolMine/polmineR", ref = "dev")`

To explain: I have refactored the cpos-method (a worker that will usually not be called directly) so that it can digest multible queries. The count, matches, kwic and context methods will now allow for multiple queries to be passed in. There was one remaining bug for this change.

Anyway, you might now try:
count("PLPRBT", query = c('"Ungleichh.*"', '"Auseinanderdriften.*"'), cqp = TRUE)
