### ISSUE TITLE
Arguments left/right in cooccurrences()-method with no effect

### ISSUE THREAD

**Issue by mxi-hug** [PolMine/polmineR#43]
if I got this right, the left/right argument in the cooccurrences-method should determine the search window for potential cooccurrences for a search term. Consequently, the following lines should return different results

```
test_10 <- cooccurrences("GERMAPARL", query = '"Arbeit"', cqp = T, left = 5, right = 10)
test_5 <- cooccurrences("GERMAPARL", query = '"Arbeit"', cqp = T, left = 5, right = 5)
```

as the results returned are the same, it is probably the default value of 15 which is used.

**Comment by PolMine** [comment]
Very important issue! It did/does not occur when the `cooccurrences()`-method was applied to a `partition`-object. The issue occurs because the main worker behind the `cooccurrences`-method is the `context()`-method, which is only implemented for `partition`-objects. When the `cooccurrences()`-method is called on a character string (i.e. a corpus), a partition is generated that covers the entire corpus, but the arguments `left` and `right` were just not passed to the `cooccurrences()`-method (for partition) that is called subsequently. So this is why left and right was ineffective. The solution is obvious (passing the arguments) and is implemented in the next development version I plan to push today.
