### ISSUE TITLE
Faulty cqp-syntax leads to total crash of R

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#46]
A single quotation mark in the wrong place crashes the entire R session. See wrong quotation mark before OR-Operator.   

```
count("MIGPARL", query = "'(.*[Aa]usländerbeauftragt.*'|.*[Ii]ntegrationsbeauftragt.*)", cqp = TRUE, breakdown = TRUE)
```

Feature Request: A welcome feature would be an error message "invalid cqp query".

**Comment by PolMine** [comment]
Good point. I have just pushed a new version of polmineR (dev branch) that includes a new function `cqp_check_query` that checks a query so that opening quotation marks are matched by closing quotation marks - which is presumably the the most common error in CQP queries. 

This new function is used in the `cpos()`-method, which is the actual worker to get the matches for (CQP) queries, and a new logical argument `check` can be used to check the validity of the query. All methods that call `cpos()` (such as `kwic()`, `count()`, `cooccurrences()` etc) now also have this argument, and pass it to the call of `cpos()`.

However, the example you chose is really tricky: The number of opening/closing quotation marks is ok, but the closing quotation mark is at the wrong place. I hope the new check functionality makes sense, by making it easier to understand what goes wrong with a CQP query. But it does not yet solve the issue you came across.

At the end of the day, I do not think this is a polmineR issue, but rather something that should be addressed in a more robust version of RcppCWB. Let's keep this issue open to come back to it ...

**Comment by PolMine** [comment]
Dear Christoph,

finally, I managed to look into what happens in the RcppCWB package, i.e. why a faulty CQP syntax provokes a crash.

A slight modification of the C code of CQP solves the issue. The next release of RcppCWB (v0.2.7) will include the fix. As I am sure not that this is not a polmineR issue, I will close the issue.

Kind regards
Andreas
