### ISSUE TITLE
Shiny | Mail crashes when no mail is set

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#61]
Clicking on the mail icon leads to a crash of the shiny app. R says: "Warning: Error in .mail: email is not set in session setting" which is logical but it would be nicer if the error is caught before the crash.

**Comment by ablaette** [comment]
Good point. I have just pushed a new polmineR version to the dev branch (v0.7.11.9029) that address this issue. You will now receive telling messages on why sending a result out by mail may have failed.

The "required authentication" message may be tricky to understand. For my organisation, the authentication requirement is fulfilled when I am logged into the network via VPN.

Please let me know whether things work now. Below the surface, I have reworked email-sending-operations and the messaging functionality of polmineR, so that messages you get in the shiny app can be implemented easily.

**Comment by PolMine** [comment]
Having reconsidered the solution I had implemented a few weeks ok, I think it adresses the issue you had raised: The shiny app will not crash if it is not possible to send out results; you get a warning message. So I close the issue.
