### ISSUE TITLE
enrich for subcorpus class?

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#78]
`
subset_a <- subset("MIGPARL", regional_state = "BY") %>% enrich(p_attribute = "word")
`

Doesn't work. In the examples for `features`, there is the hint that 

`
subset_a <- subset("MIGPARL", regional_state = "BY") %>% count(p_attribute = "word")
`

does work.

This could be backwards compatible or at least more explicit for people who are used to the enrichment workflow.

**Comment by ablaette** [comment]
As I would see it, this is a matter of documentation. The subcorpus class inherits from the `regions`and the `corpus`class, and intentionally does not store quantitative evaluations of subcorpora. This is what the `partition`class can do, as a hybrid class between the corpus/regions/subcorpus-class and the classes inheriting from the `textstat` class. 

Backwards compatibility is ensured, because old, partition-class-based workflows do work as before. However, the new subset/split-workflows are not made available for the partition-class.

Would be great to hear whether this is sufficiently plausible and whether improved documentation would solve the issue you raised.

**Comment by ChristophLeonhardt** [comment]
I have to admit, the logic is sound and I am not even sure if there is a huge need for further documentation. The enrich-method is quite specific about the objects it is applicable for already.

Maybe one could include a subset(...) %>% count(...) example in the subcorpus man files, but as I said, I am not sure if there is really a need for it if you don't want to use partition and subcorpus interchangeably.

**Comment by ablaette** [comment]
Thanks for the feedback. A new version of polmineR I just pushed on the dev branch (v0.7.11.9015) includes more elaborated documentation. To avoid collapsing too many aspects into a single documentation object, there is now a documentation entry for the `subcorpus` class (`?subcorpus`), and and documentation entry for using `subset` on corpora and subcorpora (`?subset`). 

Documentation of the `subcorpus` includes an examble for the `count()`-method, as suggested.

Admittedly, this is not yet the end of improving the documentation...

**Comment by ablaette** [comment]
Having returned to this issue after a while, I am confident we can close it. However, I have added the following explanatory sentences to the "see also" section of the documentation of the `subcorpus`class:  

"The `subcorpus` class shares many features with the `partition` class, but it is more parsimonious and does not include information on statistical properties of the subcorpus (i.e. a count table). In line with this logic, the `subcorpus` class inherits from the `corpus` class, whereas the `partition` class inherits from the `textstat` class."
