### ISSUE TITLE
Can't scroll in interactive labelling view when using Handsontable

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#79]
Let's assume I want to label a kwic object with 214 hits:

```{r}
library(polmineR) 
use("GermaParl")

  x <- context("GERMAPARL", query = '".*[Kk]onflikt.*"', positivelist = c("Irak", "Afghanistan"), cqp = TRUE, left = 15, right = 15) %>%
  kwic()

label(x, js = "Handsontable")
```

Neither in the Viewer Pane nor in Full Screen mode (i.e. in the browser) I can see the entire list of 214 hits, because I cannot scroll down / switch pages. Probably a minor shiny preference?

**Comment by ablaette** [comment]
I think this has been solved in the meantime. The table can now be scrolled. See the example which I have edited slightly, because the `label()`-method has been replaced by the `edit()` standard generic.

```r
library(polmineR) 
use("GermaParl")

x <- corpus("GERMAPARL") %>%
  context(
    query = '".*[Kk]onflikt.*"',
    positivelist = c("Irak", "Afghanistan"),
    cqp = TRUE,
    left = 15,
    right = 15
  ) %>%
  kwic()

edit(x)
```

The only remaining limitation is that the size of the table is fixed in pixels, so you have to adjust the size of the viewer pane. It is really hard (i.e. I could not find a solution) to omit that. But maybe this is something we can live with?
