### ISSUE TITLE
Error in pipe when using partition() and getting s_attributes

### ISSUE THREAD

**Issue by KevinGlock** [PolMine/polmineR#97]
Hi,

you offered an example of a pipe in partition:
```
bt2008min <- "GERMAPARL" %>% 
  partition(year = 2008) %>%
  partition(interjection = FALSE) %>%
  partition(role = c("mp", "government"))
```
and I wanted to manipulate it, but it doesn´t work.
```
coi_r <- "GERMAPARL" %>%
partition(party = c("CDU", "CSU")) %>%
partition(interjection = F) %>%
partition(encoding = "latin1") %>%
partition(p_attribute = "word") %>%
partition(role = c("mp", "government"))
```
I got rid of the pipes backwards. And the error doesn´t occur when not including the last two pipes.

The returning error is:

``` f
... get encoding: latin1
... get cpos and strucs
... Setting up partition 
... getting cpos and strucs
Error in .local(.Object, ...) : 
  some or all s-attributes provided are not available
```
The odd way works very well. 
```
coi_r <- partition("GERMAPARL",
    party = c(
      "CDU", "CSU"),
    interjection= F,
    encoding = "latin1",
    p_attribute = "word",
    role = c("mp", "government")
  ) ## works very well
```
It is not a big problem since the workflow is unaffected. I only want to let you know.

**Comment by ablaette** [comment]
Actually, this is not a bug. I think I would consider the "odd way" the ordinary way to define a partition using a set of s-attributes. My only comment is that it is actually not necessary to use the argument `p_attribute`, because upon defining a partition, the encoding of the corpus is read from the registry file defining the corpus anyway.

The behavior of the pipe that throws an error is not surprising. In lines four (`partition(encoding = "latin1")`) and five (`partition(p_attribute = "word")`) you do not offer any s-attribute that could be used to further subset the partition that has been previously defined. Offering the arguments `encoding` or `p_attribute` does not supply the s-attribute that is required.

Admittedly the error message might be somewhat more informative, so next versions of polmineR will tell you that the statement of a s-attribute is missing.

**Comment by KevinGlock** [comment]
Thank you for your explanation.
Actually I meant ordinary, my fault...sorry.
